// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dbwncraitzdultdumhfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRid25jcmFpdHpkdWx0ZHVtaGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjYzOTcsImV4cCI6MjA3MDAwMjM5N30.jcfnBoB46oksQ10tpterUzZHf78cWvtkSL7wNQsbAMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);