// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xobeppegcmwplkoezgur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvYmVwcGVnY213cGxrb2V6Z3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzAwODEsImV4cCI6MjA2OTU0NjA4MX0.Ga01bkRyaE7J8_YqphNd525lvjyI9L8tuQTXz1odOWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});